version: '3.4'

services:
    nginx:
        # @see https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-nginx-dev.html#customization
        image: webdevops/php-nginx-dev:8.2
        volumes:
            - ./:/app
        working_dir: /app


